// app/layout.jsx
import "./globals.css";
import Script from "next/script";
import { Roboto } from "next/font/google";

// components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Matthew Chang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} dark`} // default dark on SSR to avoid flash
      suppressHydrationWarning
    >
      <head>
        {/* Apply saved theme ASAP to avoid flash */}
        <Script id="theme-init" strategy="beforeInteractive">
          {`
            try {
              const saved = localStorage.getItem('theme'); // 'dark' | 'light'
              const useDark = saved ? saved === 'dark' : true; // default dark
              document.documentElement.classList.toggle('dark', useDark);
            } catch {}
          `}
        </Script>
      </head>

      <body>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
